### PR TITLE
Update formatter.rb

### PR DESCRIPTION
**Pull request by Paradoxxal**
An error occurred while running tests

### CODE REVIEW

**Comment by rosskevin** [comment]
Did the api change?  If so, will you bump the minimum version on cucumber to the relevant version?

**Comment by Paradoxxal** [comment]
Now we use cucumber - 2.4.0

**Comment by rosskevin** [comment]
> will you bump the minimum version on cucumber to the relevant version?

**Comment by Paradoxxal** [comment]
What does it mean - "relevant version"? What shall I do?

**Comment by rosskevin** [comment]
Update the gemspec with the minimum version needed for this code to work.  As-is, your code would allow older version of cucumber which may not work.

**Comment by rosskevin** [comment]
@Paradoxxal - I have updated all gems and all specs run fine.  I don't see the need to change this, can you point me to an issue or source change that would require this change?  Or provide a breaking spec that this fixes?

**Comment by rosskevin** [comment]
I'm going to close this in favor of #11

**Pull request closed without merging**
