### PR TITLE
Additional statistics

### PR DESCRIPTION
**Pull request by callahat**
Adding scenario statistics from @codevelvet's branch
Adding specs around scenario statistics
Adding feature statistics and specs

### CODE REVIEW

**Comment by rosskevin** [comment]
Have you manually tested? Good to merge and release as-is? Thanks!

**Comment by rosskevin** [comment]
@callahat? any response?

**Comment by callahat** [comment]
Yup, ran it with a project to gather stats and it worked.


 
 
  On Thu, Aug 4, 2016 at 11:16 AM, Kevin Ross<notifications@github.com> wrote:   
@callahat? any response?

**Comment by rosskevin** [comment]
Pushed to rubygems as 2.2.0, thank you!

**Pull request merged**
